In [1]:
import pandas as pd

In [2]:
df_train = pd.read_csv('train.csv')

In [3]:
df_test = pd.read_csv('test.csv')

In [4]:
df_train.columns

Index(['id', 'Brand', 'Material', 'Size', 'Compartments', 'Laptop Compartment',
       'Waterproof', 'Style', 'Color', 'Weight Capacity (kg)', 'Price'],
      dtype='object')

In [5]:
df_train['Weight Capacity (kg)'].fillna(df_train['Weight Capacity (kg)'].mean(),inplace=True)
df_test['Weight Capacity (kg)'].fillna(df_test['Weight Capacity (kg)'].mean(),inplace=True)
df_train['Brand'].fillna(df_train['Brand'].mode()[0],inplace=True)
df_test['Brand'].fillna(df_test['Brand'].mode()[0],inplace=True)
df_train['Material'].fillna(df_train['Material'].mode()[0],inplace=True)
df_test['Material'].fillna(df_test['Material'].mode()[0],inplace=True)
df_train['Size'].fillna(df_train['Size'].mode()[0],inplace=True)
df_test['Size'].fillna(df_test['Size'].mode()[0],inplace=True)
df_train['Laptop Compartment'].fillna(df_train['Laptop Compartment'].mode()[0],inplace=True)
df_test['Laptop Compartment'].fillna(df_test['Laptop Compartment'].mode()[0],inplace=True)
df_train['Waterproof'].fillna(df_train['Waterproof'].mode()[0],inplace=True)
df_test['Waterproof'].fillna(df_test['Waterproof'].mode()[0],inplace=True)
df_train['Style'].fillna(df_train['Style'].mode()[0],inplace=True)
df_test['Style'].fillna(df_test['Style'].mode()[0],inplace=True)
df_train['Color'].fillna(df_train['Color'].mode()[0],inplace=True)
df_test['Color'].fillna(df_test['Color'].mode()[0],inplace=True)

C:\Users\91736\AppData\Local\Temp\ipykernel_24560\4016697978.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_train['Weight Capacity (kg)'].fillna(df_train['Weight Capacity (kg)'].mean(),inplace=True)
C:\Users\91736\AppData\Local\Temp\ipykernel_24560\4016697978.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_test['Weight Capacity (kg)'].fillna(df_test['Weight Capacity (kg)'].mean(),inplace=True)
C:\Users\91736\AppData\Local\Temp\ipykernel_24560\4016697978.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_train['Brand'].fillna(df_train['Brand'].mode()[0],inplace=True)
C:\Users\91736\AppData\Local\Temp\ipykernel_24560\4016697978.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_test['Brand'].fillna(df_test['Brand'].mode()[0],inplace=True)
C:\Users\91736\AppData\Local\Temp\ipykernel_24560\4016697978.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_train['Material'].fillna(df_train['Material'].mode()[0],inplace=True)
C:\Users\91736\AppData\Local\Temp\ipykernel_24560\4016697978.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_test['Material'].fillna(df_test['Material'].mode()[0],inplace=True)
C:\Users\91736\AppData\Local\Temp\ipykernel_24560\4016697978.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_train['Size'].fillna(df_train['Size'].mode()[0],inplace=True)
C:\Users\91736\AppData\Local\Temp\ipykernel_24560\4016697978.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_test['Size'].fillna(df_test['Size'].mode()[0],inplace=True)
C:\Users\91736\AppData\Local\Temp\ipykernel_24560\4016697978.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_train['Laptop Compartment'].fillna(df_train['Laptop Compartment'].mode()[0],inplace=True)
C:\Users\91736\AppData\Local\Temp\ipykernel_24560\4016697978.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_test['Laptop Compartment'].fillna(df_test['Laptop Compartment'].mode()[0],inplace=True)
C:\Users\91736\AppData\Local\Temp\ipykernel_24560\4016697978.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_train['Waterproof'].fillna(df_train['Waterproof'].mode()[0],inplace=True)
C:\Users\91736\AppData\Local\Temp\ipykernel_24560\4016697978.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_test['Waterproof'].fillna(df_test['Waterproof'].mode()[0],inplace=True)
C:\Users\91736\AppData\Local\Temp\ipykernel_24560\4016697978.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_train['Style'].fillna(df_train['Style'].mode()[0],inplace=True)
C:\Users\91736\AppData\Local\Temp\ipykernel_24560\4016697978.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_test['Style'].fillna(df_test['Style'].mode()[0],inplace=True)
C:\Users\91736\AppData\Local\Temp\ipykernel_24560\4016697978.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_train['Color'].fillna(df_train['Color'].mode()[0],inplace=True)
C:\Users\91736\AppData\Local\Temp\ipykernel_24560\4016697978.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_test['Color'].fillna(df_test['Color'].mode()[0],inplace=True)

In [6]:
df_test.isnull().sum()

id                      0
Brand                   0
Material                0
Size                    0
Compartments            0
Laptop Compartment      0
Waterproof              0
Style                   0
Color                   0
Weight Capacity (kg)    0
dtype: int64

In [7]:
df_train.isnull().sum()

id                      0
Brand                   0
Material                0
Size                    0
Compartments            0
Laptop Compartment      0
Waterproof              0
Style                   0
Color                   0
Weight Capacity (kg)    0
Price                   0
dtype: int64

In [8]:
df_train.to_csv("train_cleaned.csv")
df_test.to_csv('tst_cleaned.csv')

In [9]:
df_train

,id,Brand,Material,Size,Compartments,Laptop Compartment,Waterproof,Style,Color,Weight Capacity (kg),Price
0,0,Jansport,Leather,Medium,7.0,Yes,No,Tote,Black,11.611723,112.15875
1,1,Jansport,Canvas,Small,10.0,Yes,Yes,Messenger,Green,27.078537,68.88056
2,2,Under Armour,Leather,Small,2.0,Yes,No,Messenger,Red,16.643760,39.17320
3,3,Nike,Nylon,Small,8.0,Yes,No,Messenger,Green,12.937220,80.60793
4,4,Adidas,Canvas,Medium,1.0,Yes,Yes,Messenger,Green,17.749338,86.02312
...,...,...,...,...,...,...,...,...,...,...,...
299995,299995,Adidas,Leather,Small,9.0,No,No,Tote,Blue,12.730812,129.99749
299996,299996,Jansport,Leather,Large,6.0,No,Yes,Tote,Blue,26.633182,19.85819
299997,299997,Puma,Canvas,Large,9.0,Yes,Yes,Backpack,Pink,11.898250,111.41364
299998,299998,Adidas,Nylon,Small,1.0,No,Yes,Tote,Pink,6.175738,115.89080
299999,299999,Under Armour,Canvas,Small,2.0,No,Yes,Backpack,Black,18.568865,26.72762

In [10]:
x = df_train.drop(columns=['Price']) #Independent Columns
y = df_train['Price']